name = "forsynth"
version = "0.4.0"
license = "GPL-3.0-or-later"
author = "Vincent Magnin"
maintainer = "Vincent Magnin"
copyright = "2021-2025 Vincent Magnin"
description = "A Fortran synthesizer library to explore sound synthesis, sound effects, electronic music, algorithmic music, etc. Humbly follow the steps of Stockhausen, Kraftwerk and the Daft Punk!"
categories = ["music"]
keywords = ["wav", "synthesizer"]
homepage = "https://github.com/vmagnin/forsynth"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = true
test = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
