name = "forsynth"
version = "0.2.0"
license = "GPL-3.0-or-later"
author = "Vincent Magnin"
maintainer = "Vincent Magnin"
copyright = "2021-2024 Vincent Magnin"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[library]
source-dir="src"

[[test]]
name="runTests"
source-dir="test"
main="main.f90"

[[example]]
name = "demo1"
source-dir = "example"
main = "demo1.f90"

[[example]]
name = "demo2"
source-dir = "example"
main = "demo2.f90"

[[example]]
name = "demo3"
source-dir = "example"
main = "demo3.f90"

[[example]]
name = "demo4"
source-dir = "example"
main = "demo4.f90"

[[example]]
name = "drum_machine"
source-dir = "example"
main = "drum_machine.f90"
