name = "forsynth"
version = "0.4.0"
license = "GPL-3.0-or-later"
author = "Vincent Magnin"
maintainer = "Vincent Magnin"
copyright = "2021-2025 Vincent Magnin"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = false
test = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

