add_sine_wave – ForSynth
add_sine_wave Subroutine
GNU Free Documentation License
21 statements
Source File
public subroutine add_sine_wave(tape, track, t1, t2, f, Amp, envelope)
Adds on the track a sine wave with an ADSR envelope:
Arguments
Type Intent Optional Attributes Name
type(tape_recorder), intent(inout) :: tape
integer, intent(in) :: track
real(kind=wp), intent(in) :: t1
real(kind=wp), intent(in) :: t2
real(kind=wp), intent(in) :: f
real(kind=wp), intent(in) :: Amp
type(ADSR_envelope), intent(in), optional :: envelope
Calls
Called by
Source Code
    subroutine add_sine_wave(tape, track, t1, t2, f, Amp, envelope)
        type(tape_recorder), intent(inout) :: tape
        integer, intent(in)  :: track
        real(wp), intent(in) :: t1, t2, f, Amp
        type(ADSR_envelope), optional, intent(in) :: envelope
        ! Phase at t=0 s, radians:
        real(wp), parameter  :: phi = 0.0_wp
        ! Pulsation (radians/second):
        real(wp) :: omega
        ! Time in seconds:
        real(wp) :: t
        ! ADSR Envelope value:
        real(wp) :: env
        real(wp) :: signal
        integer  :: i
        env = 1._wp     ! Default value if no envelope is passed
        omega = 2.0_wp * PI * f
        do concurrent(i = nint(t1*RATE) : nint(t2*RATE)-1)
            t = (i - nint(t1*RATE)) * dt
            if (present(envelope)) env = envelope%get_level(t1+t, t1, t2)
            signal = Amp * sin(omega*t + phi) * env
            tape%left(track, i)  = tape%left(track, i)  + signal
            tape%right(track, i) = tape%right(track, i) + signal
        end do
    end subroutine add_sine_wave
Call graph
add_sine_wave calls adsr_level
add_morse_code calls add_sine_wave
add_note calls add_sine_wave
all_signals calls add_sine_wave
add_chord calls add_note
radioactivity calls add_morse_code, add_chord
chords_and_melody calls add_chord
demo_effects calls add_chord