amplitude – ForSynth
amplitude Function
GNU Free Documentation License
12 statements
Source File
pure function amplitude(freq)
Envelope of the glissando. A gaussian, plus linear sections at the extremities, to reach the 0 level.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: freq
Return Value real(kind=wp)
Calls
Called by
Call graph
amplitude calls linear1, linear2
write_amplitude_envelope calls amplitude
shepard_risset_glissando calls amplitude, write_amplitude_envelope