clear_tracks – ForSynth
clear_tracks Subroutine
GNU Free Documentation License
5 statements
Source File
public subroutine clear_tracks(self)
Erase all tracks on all the channels of the tape.
Type Bound
tape_recorder
Arguments
Type Intent Optional Attributes Name
class(tape_recorder), intent(inout) :: self
Called by
Call graph
new calls clear_tracks
create_wav_file calls new
sonify_from_array calls create_wav_file
all_signals calls create_wav_file
arpeggios calls create_wav_file
blues calls create_wav_file
chords_and_melody calls create_wav_file
demo_effects calls create_wav_file
doppler_effect calls create_wav_file
drone_music calls create_wav_file
drum_machine calls create_wav_file
four_thirty_three calls create_wav_file
misc_sounds calls create_wav_file
multiplication_bells calls create_wav_file
radioactivity calls create_wav_file
shepard_risset_glissando calls create_wav_file
shepard_scale calls create_wav_file
sonify_from_file calls sonify_from_array