create_WAV_file – ForSynth
create_WAV_file Subroutine
GNU Free Documentation License
10 statements
Source File
public subroutine create_WAV_file(self, filename, tracks, duration)
Create a WAV file with a header:
Type Bound
WAV_file
Arguments
Type Intent Optional Attributes Name
class(WAV_file), intent(inout) :: self
character(len=*), intent(in) :: filename
integer, intent(in) :: tracks
real(kind=wp), intent(in) :: duration
Calls
Called by
Source Code
    subroutine create_WAV_file(self, filename, tracks, duration)
        class(WAV_file), intent(inout) :: self
        character(*), intent(in)       :: filename
        integer, intent(in)  :: tracks
        real(wp), intent(in) :: duration
        call self%new(tracks, duration)
        self%filename   = filename
        open(newunit=self%fileunit, file=self%filename, access='stream', status='replace', action='write')
        call self%write_header()
    end subroutine create_WAV_file
Call graph
create_wav_file calls new, write_header
new calls clear_tracks
sonify_from_array calls create_wav_file
all_signals calls create_wav_file
arpeggios calls create_wav_file
blues calls create_wav_file
chords_and_melody calls create_wav_file
demo_effects calls create_wav_file
doppler_effect calls create_wav_file
drone_music calls create_wav_file
drum_machine calls create_wav_file
four_thirty_three calls create_wav_file
misc_sounds calls create_wav_file
multiplication_bells calls create_wav_file
radioactivity calls create_wav_file
shepard_risset_glissando calls create_wav_file
shepard_scale calls create_wav_file
sonify_from_file calls sonify_from_array
sonify calls sonify_from_file