dB_to_linear – ForSynth
dB_to_linear Function
GNU Free Documentation License
4 statements
Source File
public pure function dB_to_linear(dB)
This function converts dB to an amplitude. At 0 dB, our amplitude reference value is 1. -6 dB is approximately 1/2 (~0.50118...). -20 dB is 1/10. https://en.wikipedia.org/wiki/Decibel
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: dB
Return Value real(kind=wp)
Called by
Call graph
apply_dynamic_effect calls db_to_linear
shepard_scale calls db_to_linear
demo_effects calls apply_dynamic_effect