finalize – ForSynth
finalize Subroutine
GNU Free Documentation License
5 statements
Source File
public subroutine finalize(self)
Called by the close_WAV_file() method.
Type Bound
tape_recorder
Arguments
Type Intent Optional Attributes Name
class(tape_recorder), intent(inout) :: self
Called by
Call graph
close_wav_file calls finalize
sonify_from_array calls close_wav_file
all_signals calls close_wav_file
arpeggios calls close_wav_file
blues calls close_wav_file
chords_and_melody calls close_wav_file
demo_effects calls close_wav_file
doppler_effect calls close_wav_file
drone_music calls close_wav_file
drum_machine calls close_wav_file
four_thirty_three calls close_wav_file
misc_sounds calls close_wav_file
multiplication_bells calls close_wav_file
radioactivity calls close_wav_file
shepard_risset_glissando calls close_wav_file
shepard_scale calls close_wav_file
sonify_from_file calls sonify_from_array