get_name – ForSynth
get_name Function
GNU Free Documentation License
5 statements
Source File
public function get_name(self)
Returns the name of the WAV file:
Type Bound
WAV_file
Arguments
Type Intent Optional Attributes Name
class(WAV_file), intent(inout) :: self
Return Value character(len=len(self%filename))
Called by
Call graph
sonify_from_array calls get_name
all_signals calls get_name
arpeggios calls get_name
blues calls get_name
chords_and_melody calls get_name
demo_effects calls get_name
doppler_effect calls get_name
drone_music calls get_name
drum_machine calls get_name
four_thirty_three calls get_name
misc_sounds calls get_name
multiplication_bells calls get_name
radioactivity calls get_name
shepard_risset_glissando calls get_name
shepard_scale calls get_name
sonify_from_file calls sonify_from_array