linear1 – ForSynth
linear1 Function
GNU Free Documentation License
8 statements
Source File
pure function linear1(freq, f1, f2)
Returns an amplitude rising from 0 to 1, from f1 to f2. And 0 outside.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: freq
real(kind=wp), intent(in) :: f1
real(kind=wp), intent(in) :: f2
Return Value real(kind=wp)
Called by
Call graph
amplitude calls linear1
write_amplitude_envelope calls amplitude
shepard_risset_glissando calls amplitude, write_amplitude_envelope