mix_tracks – ForSynth
mix_tracks Subroutine
GNU Free Documentation License
34 statements
Source File
public subroutine mix_tracks(self, levels, pan)
Tracks 1 to tracks-1 are mixed on track 0.
Type Bound
tape_recorder
Arguments
Type Intent Optional Attributes Name
class(tape_recorder), intent(inout) :: self
real(kind=wp), intent(in), optional, dimension(1:self%tracks) :: levels
real(kind=wp), intent(in), optional, dimension(1:self%tracks) :: pan
Called by
Call graph
sonify_from_array calls mix_tracks
all_signals calls mix_tracks
arpeggios calls mix_tracks
blues calls mix_tracks
chords_and_melody calls mix_tracks
demo_effects calls mix_tracks
doppler_effect calls mix_tracks
drone_music calls mix_tracks
drum_machine calls mix_tracks
four_thirty_three calls mix_tracks
misc_sounds calls mix_tracks
multiplication_bells calls mix_tracks
radioactivity calls mix_tracks
shepard_risset_glissando calls mix_tracks
shepard_scale calls mix_tracks
sonify_from_file calls sonify_from_array
sonify calls sonify_from_file