write_normalized_data – ForSynth
write_normalized_data Subroutine
GNU Free Documentation License
10 statements
Source File
public subroutine write_normalized_data(self)
This method normalizes the sound amplitude on track 0, before saving the left and right channels in the WAV file.
Type Bound
WAV_file
Arguments
Type Intent Optional Attributes Name
class(WAV_file), intent(inout) :: self
Called by
Call graph
close_wav_file calls write_normalized_data
all_signals calls close_wav_file
arpeggios calls close_wav_file
blues calls close_wav_file
chords_and_melody calls close_wav_file
demo_effects calls close_wav_file
doppler_effect calls close_wav_file
drone_music calls close_wav_file
drum_machine calls close_wav_file
four_thirty_three calls close_wav_file
misc_sounds calls close_wav_file
multiplication_bells calls close_wav_file
radioactivity calls close_wav_file
shepard_risset_glissando calls close_wav_file
shepard_scale calls close_wav_file