write_amplitude_envelope – ForSynth
write_amplitude_envelope Subroutine
GNU Free Documentation License
14 statements
Source File
subroutine write_amplitude_envelope()
Useful for debugging and setting the envelope parameters:
Arguments
None
Calls
Called by
Call graph
write_amplitude_envelope calls amplitude
amplitude calls linear1, linear2
shepard_risset_glissando calls write_amplitude_envelope