four_thirty_three – ForSynth
four_thirty_three Program
GNU Free Documentation License
13 statements
Source File
Uses
wav_file_class
forsynth
A minimalist Forsynth file! And a double tribute to John Cage and Joy Division.
Calls
Variables
Type Attributes Name Initial
type(WAV_file) :: demo
Source Code
program four_thirty_three
    use forsynth, only: wp
    use wav_file_class, only: WAV_file
    implicit none
    type(WAV_file) :: demo
    ! We create a new WAV file, and define the number of tracks and its duration:
    call demo%create_WAV_file('four_thirty_three.wav', tracks=1, duration=4*60._wp + 33)
    print *, "**** Creating " // demo%get_name() // " ****"
    ! All tracks will be mixed on track 0.
    ! Needed even if there is only one track!
    call demo%mix_tracks()
    call demo%close_WAV_file()
    print *,"You can now play the file ", demo%get_name()
    print *
    print *,'"Listen to the silence, let it ring on"'
end program four_thirty_three
Call graph
four_thirty_three calls close_wav_file, create_wav_file, get_name, mix_tracks
close_wav_file calls finalize, write_normalized_data
create_wav_file calls new, write_header
new calls clear_tracks