multiplication_bells – ForSynth
multiplication_bells Program
GNU Free Documentation License
35 statements
Source File
Uses
forsynth
wav_file_class
signals
music
An example with a lot of bells, either periodic or random. https://en.wikipedia.org/wiki/Campanology
Calls
Variables
Type Attributes Name Initial
type(WAV_file) :: demo
real(kind=wp), parameter :: dnote = 3._wp
integer :: i
integer, parameter :: iend = 15
real(kind=wp) :: r1
real(kind=wp) :: r2
real(kind=wp) :: r3
integer, parameter :: shift(0:5) = [4, 7, 10, 12, 16, 19]
real(kind=wp), parameter :: t2 = 75._wp
Source Code
program multiplication_bells
    use forsynth, only: wp
    use wav_file_class, only: WAV_file, tape_recorder
    use music, only: SEMITONE, PITCH
    use signals, only: add_bell
    implicit none
    type(WAV_file) :: demo
    ! Total duration in seconds:
    real(wp), parameter :: t2 = 75._wp
    ! Duration of the basic note:
    real(wp), parameter :: dnote = 3._wp
    ! Semitones for major third, fifth, 7th, octave, major third, fifth:
    integer, parameter :: shift(0:5) = [ 4, 7, 10, 12, 16, 19 ]
    integer, parameter  :: iend = 15    ! Nb of periods for the periodic bells
    integer  :: i               ! Loop counter
    real(wp) :: r1, r2, r3      ! Random numbers
    ! We create a new WAV file, and define the number of tracks and its duration:
    call demo%create_WAV_file('multiplication_bells.wav', tracks=1, duration=t2)
    print *, "**** Creating " // demo%get_name() // " ****"
    print *, "Be patient, it may take up to one minute..."
    associate(tape => demo%tape_recorder)
    ! Intro:
    call add_bell(tape, track=1, t1=0._wp, f=PITCH*SEMITONE**(-7), Amp=2._wp)
    ! Periodic bells:
    do i = 1, iend
        call add_bell(tape, track=1, t1=i*dnote,             f=PITCH*SEMITONE**(-4), Amp=1._wp)
        call add_bell(tape, track=1, t1=i*dnote + dnote/4,   f=PITCH*SEMITONE**(0) , Amp=1._wp)
        call add_bell(tape, track=1, t1=i*dnote + 3*dnote/4, f=PITCH*SEMITONE**(0) , Amp=1._wp)
    end do
    ! Random bells:
    do i = 1, 100
        call random_number(r1)  ! Starting time
        call random_number(r2)  ! Tone
        call random_number(r3)  ! Amplitude
        call add_bell(tape, track=1, t1=4._wp + (iend-2)*dnote*r1, f=PITCH*SEMITONE**(shift(int(r2*6))), Amp=1._wp*r3)
    end do
    ! Outro:
    call add_bell(tape, track=1, t1=(iend+2)*dnote, f=PITCH*SEMITONE**(-7), Amp=2._wp)
    end associate
    ! All tracks will be mixed on track 0.
    ! Needed even if there is only one track!
    call demo%mix_tracks()
    call demo%close_WAV_file()
    print *,"You can now play the file ", demo%get_name()
end program multiplication_bells
Call graph
multiplication_bells calls add_bell, close_wav_file, create_wav_file, get_name, mix_tracks
add_bell calls fit_exp
close_wav_file calls finalize, write_normalized_data
create_wav_file calls new, write_header
new calls clear_tracks